packages:
  - apps/*
  - packages/*
  - packages/config/*
  - packages/trpc

ignoredBuiltDependencies:
  - '@sentry/cli'
  - supabase

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
