import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Container, Grid, GridItem, Flex, Stack, HStack, Responsive } from '../components/ui/responsive-layout';
const meta = {
    title: 'Layout/ResponsiveLayout',
    component: Container,
    parameters: {
        layout: 'padded',
    },
    tags: ['autodocs'],
};
export default meta;
// Container component
export const ContainerExample = {
    render: () => (_jsxs("div", { className: "space-y-4", children: [_jsx(Container, { maxWidth: "sm", className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { className: "text-center", children: "Small Container (max-w-screen-sm)" }) }), _jsx(Container, { maxWidth: "md", className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { className: "text-center", children: "Medium Container (max-w-screen-md)" }) }), _jsx(Container, { maxWidth: "lg", className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { className: "text-center", children: "Large Container (max-w-screen-lg)" }) }), _jsx(Container, { maxWidth: "xl", className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { className: "text-center", children: "Extra Large Container (max-w-screen-xl)" }) }), _jsx(Container, { maxWidth: "2xl", className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { className: "text-center", children: "2XL Container (max-w-screen-2xl)" }) })] })),
};
// Grid component
export const GridExample = {
    render: () => (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Basic Grid" }), _jsx(Grid, { columns: { xs: 1, sm: 2, md: 3, lg: 4 }, gap: "md", children: Array.from({ length: 8 }).map((_, i) => (_jsxs("div", { className: "bg-primary/10 p-4 rounded-lg text-center", children: ["Item ", i + 1] }, i))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Grid with Different Gap Sizes" }), _jsx(Grid, { columns: { xs: 2, md: 4 }, gap: "lg", children: Array.from({ length: 8 }).map((_, i) => (_jsxs("div", { className: "bg-accent/10 p-4 rounded-lg text-center", children: ["Item ", i + 1] }, i))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Grid with Column and Row Gaps" }), _jsx(Grid, { columns: { xs: 2, md: 4 }, rowGap: "lg", columnGap: "sm", children: Array.from({ length: 8 }).map((_, i) => (_jsxs("div", { className: "bg-accent/10 p-4 rounded-lg text-center", children: ["Item ", i + 1] }, i))) })] })] })),
};
// GridItem component
export const GridItemExample = {
    render: () => (_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Grid with Spanning Items" }), _jsxs(Grid, { columns: { xs: 4, md: 12 }, gap: "md", children: [_jsx(GridItem, { colSpan: { xs: 4, md: 6 }, className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { children: "Spans 4 columns on mobile, 6 on tablet+" }) }), _jsx(GridItem, { colSpan: { xs: 4, md: 6 }, className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { children: "Spans 4 columns on mobile, 6 on tablet+" }) }), _jsx(GridItem, { colSpan: { xs: 4, md: 4 }, className: "bg-accent/10 p-4 rounded-lg", children: _jsx("p", { children: "Spans 4 columns on mobile, 4 on tablet+" }) }), _jsx(GridItem, { colSpan: { xs: 4, md: 4 }, className: "bg-accent/10 p-4 rounded-lg", children: _jsx("p", { children: "Spans 4 columns on mobile, 4 on tablet+" }) }), _jsx(GridItem, { colSpan: { xs: 4, md: 4 }, className: "bg-accent/10 p-4 rounded-lg", children: _jsx("p", { children: "Spans 4 columns on mobile, 4 on tablet+" }) }), _jsx(GridItem, { colSpan: { xs: 4, md: 12 }, className: "bg-primary/10 p-4 rounded-lg", children: _jsx("p", { children: "Spans 4 columns on mobile, 12 (full width) on tablet+" }) })] })] })),
};
// Flex component
export const FlexExample = {
    render: () => (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Basic Flex (Row)" }), _jsxs(Flex, { gap: "md", className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Flex Column" }), _jsxs(Flex, { direction: "column", gap: "md", className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Responsive Flex (Column on Mobile, Row on Desktop)" }), _jsxs(Flex, { direction: "column", responsive: {
                            md: { direction: 'row' }
                        }, gap: "md", className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Flex with Different Alignment" }), _jsxs(Flex, { justify: "between", align: "center", className: "bg-muted/30 p-4 rounded-lg h-32", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Start" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Center" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "End" })] })] })] })),
};
// Stack component
export const StackExample = {
    render: () => (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Basic Stack" }), _jsxs(Stack, { spacing: "md", className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Stack with Dividers" }), _jsxs(Stack, { spacing: "md", dividers: true, className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] })] })),
};
// HStack component
export const HStackExample = {
    render: () => (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Basic HStack" }), _jsxs(HStack, { spacing: "md", className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "HStack with Dividers" }), _jsxs(HStack, { spacing: "md", dividers: true, className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "HStack with Different Spacing" }), _jsxs(HStack, { spacing: "lg", className: "bg-muted/30 p-4 rounded-lg", children: [_jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 1" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 2" }), _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Item 3" })] })] })] })),
};
// Responsive component
export const ResponsiveExample = {
    render: () => (_jsx("div", { className: "space-y-8", children: _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium mb-2", children: "Responsive Visibility" }), _jsxs("div", { className: "bg-muted/30 p-4 rounded-lg", children: [_jsx(Responsive, { hide: ['md', 'lg'], children: _jsx("div", { className: "bg-primary/10 p-4 rounded-lg", children: "Visible on mobile and extra large screens, hidden on medium and large screens" }) }), _jsx(Responsive, { show: ['md', 'lg'], children: _jsx("div", { className: "bg-accent/10 p-4 rounded-lg mt-4", children: "Hidden on mobile and extra large screens, visible on medium and large screens" }) })] })] }) })),
};
